//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOAPTest.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        SOAPTest.ServiceReference1.HelloWorldResponse HelloWorld(SOAPTest.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<SOAPTest.ServiceReference1.HelloWorldResponse> HelloWorldAsync(SOAPTest.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name HelloTestResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloTest", ReplyAction="*")]
        SOAPTest.ServiceReference1.HelloTestResponse HelloTest(SOAPTest.ServiceReference1.HelloTestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloTest", ReplyAction="*")]
        System.Threading.Tasks.Task<SOAPTest.ServiceReference1.HelloTestResponse> HelloTestAsync(SOAPTest.ServiceReference1.HelloTestRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public SOAPTest.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(SOAPTest.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public SOAPTest.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(SOAPTest.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloTestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloTest", Namespace="http://tempuri.org/", Order=0)]
        public SOAPTest.ServiceReference1.HelloTestRequestBody Body;
        
        public HelloTestRequest() {
        }
        
        public HelloTestRequest(SOAPTest.ServiceReference1.HelloTestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloTestRequestBody {
        
        public HelloTestRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloTestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloTestResponse", Namespace="http://tempuri.org/", Order=0)]
        public SOAPTest.ServiceReference1.HelloTestResponseBody Body;
        
        public HelloTestResponse() {
        }
        
        public HelloTestResponse(SOAPTest.ServiceReference1.HelloTestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloTestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloTestResult;
        
        public HelloTestResponseBody() {
        }
        
        public HelloTestResponseBody(string HelloTestResult) {
            this.HelloTestResult = HelloTestResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : SOAPTest.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<SOAPTest.ServiceReference1.WebService1Soap>, SOAPTest.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOAPTest.ServiceReference1.HelloWorldResponse SOAPTest.ServiceReference1.WebService1Soap.HelloWorld(SOAPTest.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            SOAPTest.ServiceReference1.HelloWorldRequest inValue = new SOAPTest.ServiceReference1.HelloWorldRequest();
            inValue.Body = new SOAPTest.ServiceReference1.HelloWorldRequestBody();
            SOAPTest.ServiceReference1.HelloWorldResponse retVal = ((SOAPTest.ServiceReference1.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SOAPTest.ServiceReference1.HelloWorldResponse> SOAPTest.ServiceReference1.WebService1Soap.HelloWorldAsync(SOAPTest.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<SOAPTest.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            SOAPTest.ServiceReference1.HelloWorldRequest inValue = new SOAPTest.ServiceReference1.HelloWorldRequest();
            inValue.Body = new SOAPTest.ServiceReference1.HelloWorldRequestBody();
            return ((SOAPTest.ServiceReference1.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOAPTest.ServiceReference1.HelloTestResponse SOAPTest.ServiceReference1.WebService1Soap.HelloTest(SOAPTest.ServiceReference1.HelloTestRequest request) {
            return base.Channel.HelloTest(request);
        }
        
        public string HelloTest() {
            SOAPTest.ServiceReference1.HelloTestRequest inValue = new SOAPTest.ServiceReference1.HelloTestRequest();
            inValue.Body = new SOAPTest.ServiceReference1.HelloTestRequestBody();
            SOAPTest.ServiceReference1.HelloTestResponse retVal = ((SOAPTest.ServiceReference1.WebService1Soap)(this)).HelloTest(inValue);
            return retVal.Body.HelloTestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SOAPTest.ServiceReference1.HelloTestResponse> SOAPTest.ServiceReference1.WebService1Soap.HelloTestAsync(SOAPTest.ServiceReference1.HelloTestRequest request) {
            return base.Channel.HelloTestAsync(request);
        }
        
        public System.Threading.Tasks.Task<SOAPTest.ServiceReference1.HelloTestResponse> HelloTestAsync() {
            SOAPTest.ServiceReference1.HelloTestRequest inValue = new SOAPTest.ServiceReference1.HelloTestRequest();
            inValue.Body = new SOAPTest.ServiceReference1.HelloTestRequestBody();
            return ((SOAPTest.ServiceReference1.WebService1Soap)(this)).HelloTestAsync(inValue);
        }
    }
}
