//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArrayOfStrings.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Hjemmeside", Namespace="http://schemas.datacontract.org/2004/07/H3SOAP")]
    [System.SerializableAttribute()]
    public partial class Hjemmeside : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BeskrivelseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool FarligField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NavnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Beskrivelse {
            get {
                return this.BeskrivelseField;
            }
            set {
                if ((object.ReferenceEquals(this.BeskrivelseField, value) != true)) {
                    this.BeskrivelseField = value;
                    this.RaisePropertyChanged("Beskrivelse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Farlig {
            get {
                return this.FarligField;
            }
            set {
                if ((this.FarligField.Equals(value) != true)) {
                    this.FarligField = value;
                    this.RaisePropertyChanged("Farlig");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Navn {
            get {
                return this.NavnField;
            }
            set {
                if ((object.ReferenceEquals(this.NavnField, value) != true)) {
                    this.NavnField = value;
                    this.RaisePropertyChanged("Navn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url {
            get {
                return this.UrlField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlField, value) != true)) {
                    this.UrlField = value;
                    this.RaisePropertyChanged("Url");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Bil", Namespace="http://schemas.datacontract.org/2004/07/H3SOAP")]
    [System.SerializableAttribute()]
    public partial class Bil : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string getBilTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int getHKField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string getBilType {
            get {
                return this.getBilTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.getBilTypeField, value) != true)) {
                    this.getBilTypeField = value;
                    this.RaisePropertyChanged("getBilType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int getHK {
            get {
                return this.getHKField;
            }
            set {
                if ((this.getHKField.Equals(value) != true)) {
                    this.getHKField = value;
                    this.RaisePropertyChanged("getHK");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/H3SOAP")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getHjemmesider", ReplyAction="http://tempuri.org/IService1/getHjemmesiderResponse")]
        ArrayOfStrings.ServiceReference1.Hjemmeside[] getHjemmesider();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getHjemmesider", ReplyAction="http://tempuri.org/IService1/getHjemmesiderResponse")]
        System.Threading.Tasks.Task<ArrayOfStrings.ServiceReference1.Hjemmeside[]> getHjemmesiderAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addHjemmesider", ReplyAction="http://tempuri.org/IService1/addHjemmesiderResponse")]
        void addHjemmesider(ArrayOfStrings.ServiceReference1.Hjemmeside h);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addHjemmesider", ReplyAction="http://tempuri.org/IService1/addHjemmesiderResponse")]
        System.Threading.Tasks.Task addHjemmesiderAsync(ArrayOfStrings.ServiceReference1.Hjemmeside h);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/givMigEnTilfeldigBil", ReplyAction="http://tempuri.org/IService1/givMigEnTilfeldigBilResponse")]
        ArrayOfStrings.ServiceReference1.Bil givMigEnTilfeldigBil();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/givMigEnTilfeldigBil", ReplyAction="http://tempuri.org/IService1/givMigEnTilfeldigBilResponse")]
        System.Threading.Tasks.Task<ArrayOfStrings.ServiceReference1.Bil> givMigEnTilfeldigBilAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        ArrayOfStrings.ServiceReference1.CompositeType GetDataUsingDataContract(ArrayOfStrings.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<ArrayOfStrings.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(ArrayOfStrings.ServiceReference1.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ArrayOfStrings.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ArrayOfStrings.ServiceReference1.IService1>, ArrayOfStrings.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ArrayOfStrings.ServiceReference1.Hjemmeside[] getHjemmesider() {
            return base.Channel.getHjemmesider();
        }
        
        public System.Threading.Tasks.Task<ArrayOfStrings.ServiceReference1.Hjemmeside[]> getHjemmesiderAsync() {
            return base.Channel.getHjemmesiderAsync();
        }
        
        public void addHjemmesider(ArrayOfStrings.ServiceReference1.Hjemmeside h) {
            base.Channel.addHjemmesider(h);
        }
        
        public System.Threading.Tasks.Task addHjemmesiderAsync(ArrayOfStrings.ServiceReference1.Hjemmeside h) {
            return base.Channel.addHjemmesiderAsync(h);
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public ArrayOfStrings.ServiceReference1.Bil givMigEnTilfeldigBil() {
            return base.Channel.givMigEnTilfeldigBil();
        }
        
        public System.Threading.Tasks.Task<ArrayOfStrings.ServiceReference1.Bil> givMigEnTilfeldigBilAsync() {
            return base.Channel.givMigEnTilfeldigBilAsync();
        }
        
        public ArrayOfStrings.ServiceReference1.CompositeType GetDataUsingDataContract(ArrayOfStrings.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<ArrayOfStrings.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(ArrayOfStrings.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
    }
}
